#Default port is 8761
server:
  port: 8761

eureka: #Netflix's Eureka config
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
  serviceUrl:
    defaultZone: http://localhost:8761

#Setting logging levels
logging:
  level:
    com.netflix: INFO
    org.springframework.web: INFO
